# Generated by Django 4.2.9 on 2024-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_question_alter_myuser_email_alter_myuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=200, null=True)),
                ('uid', models.IntegerField(max_length=100, null=True)),
                ('similarity', models.CharField(max_length=200, null=True)),
                ('userid', models.IntegerField(null=True)),
                ('que', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
