# Generated by Django 4.2.9 on 2024-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='que',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
